/**
 * HUD - Session Summary Element
 *
 * Displays a brief (<20 char) AI-generated summary of the current session.
 * The summary is generated by a standalone script (scripts/session-summary.mjs)
 * that runs in the background and caches results in the state directory.
 *
 * Generation rules:
 * - First generation after 10+ user turns
 * - Regeneration every 10 additional turns
 * - Uses `claude -p` for summarization
 */
import { dim } from '../colors.js';
/**
 * Render the session summary element.
 * Returns null if no summary is available.
 */
export function renderSessionSummary(summaryState) {
    if (!summaryState?.summary)
        return null;
    return dim('summary:') + summaryState.summary;
}
//# sourceMappingURL=session-summary.js.map